name: radeef
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  shared_preferences:
  flutter_screenutil: ^5.9.0
  flutter_svg:
  flutter_spinkit:
  flutter_otp_text_field: ^1.5.1+1
  sms_autofill: ^2.4.1
  image_picker: ^1.1.2
  camera: ^0.11.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  loading_animation_widget: ^1.3.0
  google_maps_flutter: ^2.12.3
  flutter_polyline_points: ^3.1.0
  geolocator: ^14.0.2
  flutter_rating_bar: ^4.0.1
  shimmer: 
  cached_network_image:
  socket_io_client: ^3.1.3
  get_storage: ^2.1.1
  grouped_list:
  url_launcher: ^6.3.2
  intl: ^0.20.2
  init: ^1.0.0
  onesignal_flutter: ^5.3.5
  geocoding: 


dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21


flutter:


  uses-material-design: true


  assets:
     - assets/icons/
     - assets/language/
     - assets/images/


  fonts:
     - family: Inter
       fonts:
         - asset: assets/fonts/Inter_18pt-Bold.ttf
         - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
         - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
         - asset: assets/fonts/Inter_18pt-Light.ttf
         - asset: assets/fonts/Inter_18pt-Medium.ttf
         - asset: assets/fonts/Inter_18pt-Regular.ttf
         - asset: assets/fonts/Inter_18pt-SemiBold.ttf
         - asset: assets/fonts/Inter_24pt-Bold.ttf
         - asset: assets/fonts/Inter_24pt-Regular.ttf






